
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))


###
#     The deleteRow() method deletes a row from this section.  
#     
#     Retrieve the first THEAD element and invoke the deleteRow() method
#     with an index of 0.  The nuber of rows in the THEAD section before 
#     the deletion of the row is one.  After the row is deleted the number 
#     of rows in the THEAD section is zero.
# @author NIST
# @author Rick Rivello
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-html#ID-5625626]
##
DOMTestCase('HTMLTableSectionElement22') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "tablesection", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_HTMLTableSectionElement22
    nodeList = nil
    testNode = nil
    rowsnodeList = nil
    vrows = nil
    doc = nil
    doc = load_document("tablesection", true)
      nodeList = doc.getElementsByTagName("thead")
      assertSize("Asize", 1, nodeList)
      testNode = nodeList.item(0)
      rowsnodeList = testNode.rows()
      vrows = rowsnodeList.length()
      assert_equal(1, vrows, "rowsLink1")
            testNode.deleteRow(0)
      rowsnodeList = testNode.rows()
      vrows = rowsnodeList.length()
      assert_equal(0, vrows, "rowsLink2")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/level1/html/HTMLTableSectionElement22"
  end
end

