
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))


###
#     The rows attribute returns a collection of all the rows in the table,
#     including al in THEAD, TFOOT, all TBODY elements.
#     Retrieve the rows attribute from the second TABLE element and
#     examine the items of the returned collection. 
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-html#ID-6156016]
##
DOMTestCase('HTMLTableElement07') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "table", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_HTMLTableElement07
    nodeList = nil
    rowsnodeList = nil
    testNode = nil
    doc = nil
    rowName = nil
    vrow = nil
    result = []
      
    expectedOptions = []
      expectedOptions << "tr"
      expectedOptions << "tr"
      expectedOptions << "tr"
      expectedOptions << "tr"
      
    doc = load_document("table", false)
      nodeList = doc.getElementsByTagName("table")
      assertSize("Asize", 3, nodeList)
      testNode = nodeList.item(1)
      rowsnodeList = testNode.rows()
      indexN65641 = 0
    while (indexN65641 < rowsnodeList.length)
      vrow = rowsnodeList.item(indexN65641)
    rowName = vrow.nodeName()
      result << rowName
      indexN65641 += 1
            end
      assertEqualsAutoCase("element", "rowsLink", expectedOptions, result)
        
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/level1/html/HTMLTableElement07"
  end
end

