
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001-2004 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))


###
#     The vspace attribute specifies the vertical space above and below
#     this image, applet or object.  Retrieve the vspace attribute and examine its value.  
#     
#     This test is incompatible with L2 HTML implementations due to a change in the type of the attribute.
#     
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-html#ID-22637173]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=504]
##
DOMTestCase('HTMLAppletElement09') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "applet", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_HTMLAppletElement09
    nodeList = nil
    testNode = nil
    vvspace = nil
    doc = nil
    domImpl = nil
    hasHTML2 = nil
    doc = load_document("applet", false)
      domImpl = doc.getImplementation()
      hasHTML2 = domImpl.hasFeature("HTML", "2.0")

      if (
    !hasHTML2)
        nodeList = doc.getElementsByTagName("applet")
      assertSize("Asize", 1, nodeList)
      testNode = nodeList.item(0)
      vvspace = testNode.vspace()
      assert_equal("0", vvspace, "vspaceLink")
            
         end
       
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/level1/html/HTMLAppletElement09"
  end
end

