
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
# If the "setAttributeNode(newAttr)" method replaces an
# existing Attr node with the same name, then it should
# return the previously existing Attr node.
# Retrieve the last child of the third employee and add a
# new attribute node.  The new attribute node is "street",
# which is already present in this Element.  The method
# should return the existing Attr node(old "street" Attr).
# This test uses the "createAttribute(name)" method
# from the Document interface.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-887236154]
##
DOMTestCase('elementreplaceexistingattributegevalue') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staff", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_elementreplaceexistingattributegevalue
    doc = nil
    elementList = nil
    testEmployee = nil
    newAttribute = nil
    streetAttr = nil
    value = nil
    doc = load_document("staff", true)
      elementList = doc.getElementsByTagName("address")
      testEmployee = elementList.item(2)
      newAttribute = doc.createAttribute("street")
      streetAttr = testEmployee.setAttributeNode(newAttribute)
      value = streetAttr.value()
      assert_equal("No", value, "streetNo")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/elementreplaceexistingattributegevalue"
  end
end

