
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001-2004 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require 'dom_test_case'

###
#    Create a list of all the attributes of the last child
#    of the first "p" element by using the "getAttributes()"
#    method.
# @author Curt Arnold
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-84CF096]
# see[http://lists.w3.org/Archives/Public/www-dom-ts/2002Mar/0002.html]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=184]
##
DOMTestCase('hc_elementretrieveallattributes') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "hc_staff", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_hc_elementretrieveallattributes
    doc = nil
    addressList = nil
    testAddress = nil
    attributes = nil
    attribute = nil
    attributeName = nil
    actual = []
      
    htmlExpected = []
      htmlExpected << "title"
      
    expected = []
      expected << "title"
      expected << "dir"
      
    doc = load_document("hc_staff", false)
      addressList = doc.getElementsByTagName("acronym")
      testAddress = addressList.item(0)
      attributes = testAddress.attributes()
      indexid3539572 = 0
    while (indexid3539572 < attributes.length)
      attribute = attributes.item(indexid3539572)
    attributeName = attribute.nodeName()
      actual << attributeName
      indexid3539572 += 1
            end
      
      if (("text/html" == getContentType()))
        assertEqualsIgnoreCase("htmlAttributeNames", htmlExpected, actual)

          else
            assertEqualsIgnoreCase("attributeNames", expected, actual)

         end
       
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/hc_elementretrieveallattributes"
  end
end

