
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require 'dom_test_case'

###
#     The "setNamedItem(arg)" method adds a node using its 
#    nodeName attribute. 
#    
#    Retrieve the second employee and create a NamedNodeMap 
#    object from the attributes of the last child by
#    invoking the "getAttributes()" method.  Once the
#    list is created an invocation of the "setNamedItem(arg)"
#    method is done with arg=newAttr, where newAttr is a
#    new Attr Node previously created.  The "setNamedItem(arg)"
#    method should add then new node to the NamedNodeItem 
#    object by using its "nodeName" attribute("district').
#    This node is then retrieved using the "getNamedItem(name)"
#    method.  This test uses the "createAttribute(name)"
#    method from the document interface.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1025163788]
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-349467F9]
##
DOMTestCase('namednodemapsetnameditem') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staff", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_namednodemapsetnameditem
    doc = nil
    elementList = nil
    newAttribute = nil
    testAddress = nil
    attributes = nil
    districtNode = nil
    attrName = nil
    setNode = nil
    doc = load_document("staff", true)
      elementList = doc.getElementsByTagName("address")
      testAddress = elementList.item(1)
      newAttribute = doc.createAttribute("district")
      attributes = testAddress.attributes()
      setNode = attributes.setNamedItem(newAttribute)
      districtNode = attributes.getNamedItem("district")
      attrName = districtNode.nodeName()
      assert_equal("district", attrName, "namednodemapSetNamedItemAssert")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/namednodemapsetnameditem"
  end
end

