
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001-2004 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#    Create a NamedNodeMap object from the attributes of the
#    last child of the third "p" element and traverse the
#    list from index 0 thru length -1.  All indices should
#    be valid.
# @author Curt Arnold
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-84CF096]
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-349467F9]
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-6D0FB19E]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=250]
##
DOMTestCase('hc_namednodemapchildnoderange') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "hc_staff", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_hc_namednodemapchildnoderange
    doc = nil
    elementList = nil
    testEmployee = nil
    attributes = nil
    child = nil
    strong = nil
    length = nil
    doc = load_document("hc_staff", false)
      elementList = doc.getElementsByTagName("acronym")
      testEmployee = elementList.item(2)
      attributes = testEmployee.attributes()
      length = attributes.length()
      
      if (("text/html" == getContentType()))
        assert_equal(2, length, "htmlLength")
            
          else
            assert_equal(3, length, "length")
            child = attributes.item(2)
      assert_not_nil(child, "attr2")
      
         end
       child = attributes.item(0)
      assert_not_nil(child, "attr0")
      child = attributes.item(1)
      assert_not_nil(child, "attr1")
      child = attributes.item(3)
      assert_nil(child, "attr3")
      
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/hc_namednodemapchildnoderange"
  end
end

