
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001-2003 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require 'dom_test_case'

###
#     The "insertBefore(newChild,refChild)" method inserts the
#     node "newChild" before the node "refChild". 
#     
#     Insert a newly created Element node before the second
#     sup element in the document and check the "newChild"
#     and "refChild" after insertion for correct placement.
# @author Curt Arnold
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-952280727]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=246]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=247]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=261]
##
DOMTestCase('hc_nodeinsertbefore') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "hc_staff", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_hc_nodeinsertbefore
    doc = nil
    elementList = nil
    employeeNode = nil
    childList = nil
    refChild = nil
    newChild = nil
    child = nil
    childName = nil
    insertedNode = nil
    actual = []
      
    expected = []
      expected << "em"
      expected << "strong"
      expected << "code"
      expected << "br"
      expected << "sup"
      expected << "var"
      expected << "acronym"
      
    nodeType = nil
    doc = load_document("hc_staff", true)
      elementList = doc.getElementsByTagName("sup")
      refChild = elementList.item(2)
      employeeNode = refChild.parentNode()
      childList = employeeNode.childNodes()
      newChild = doc.createElement("br")
      insertedNode = employeeNode.insertBefore(newChild, refChild)
      indexid4360935 = 0
    while (indexid4360935 < childList.length)
      child = childList.item(indexid4360935)
    nodeType = child.nodeType()
      
      if (equals(1, nodeType))
        childName = child.nodeName()
      actual << childName
      
         end
       indexid4360935 += 1
            end
      assertEqualsAutoCase("element", "nodeNames", expected, actual)
        
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/hc_nodeinsertbefore"
  end
end

