
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require 'dom_test_case'

###
#     The "cloneNode(deep)" method returns a copy of the node
#     only if deep=false.
#     
#     Retrieve the second employee and invoke the
#     "cloneNode(deep)" method with deep=false.   The
#     method should only clone this node.   The NodeName and
#     length of the NodeList are checked.   The "getNodeName()"
#     method should return "employee" and the "getLength()"
#     method should return 0.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-3A0ED0A4]
##
DOMTestCase('nodeclonenodefalse') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staff", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_nodeclonenodefalse
    doc = nil
    elementList = nil
    employeeNode = nil
    clonedNode = nil
    cloneName = nil
    cloneChildren = nil
    length = nil
    doc = load_document("staff", true)
      elementList = doc.getElementsByTagName("employee")
      employeeNode = elementList.item(1)
      clonedNode = employeeNode.cloneNode(false)
      cloneName = clonedNode.nodeName()
      assert_equal("employee", cloneName, "name")
            cloneChildren = clonedNode.childNodes()
      length = cloneChildren.length()
      assert_equal(0, length, "length")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/nodeclonenodefalse"
  end
end

