
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001-2003 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     If the "newChild" is already in the tree, it is first
#     removed before the new one is added.
#    
#     Retrieve the second "p" and replace "acronym" with its "em".
# @author Curt Arnold
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-785887307]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=246]
##
DOMTestCase('hc_nodereplacechildnewchildexists') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "hc_staff", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_hc_nodereplacechildnewchildexists
    doc = nil
    elementList = nil
    employeeNode = nil
    childList = nil
    oldChild = nil;

    newChild = nil;

    child = nil
    childName = nil
    childNode = nil
    actual = []
      
    expected = []
      expected << "strong"
      expected << "code"
      expected << "sup"
      expected << "var"
      expected << "em"
      
    replacedChild = nil
    nodeType = nil
    doc = load_document("hc_staff", true)
      elementList = doc.getElementsByTagName("p")
      employeeNode = elementList.item(1)
      childList = employeeNode.getElementsByTagName("*")
      newChild = childList.item(0)
      oldChild = childList.item(5)
      replacedChild = employeeNode.replaceChild(newChild, oldChild)
      assertSame("return_value_same", oldChild, replacedChild)
indexid4656856 = 0
    while (indexid4656856 < childList.length)
      childNode = childList.item(indexid4656856)
    childName = childNode.nodeName()
      nodeType = childNode.nodeType()
      
      if (equals(1, nodeType))
        actual << childName
      
          else
            assert_equal(3, nodeType, "textNodeType")
            assert_equal("#text", childName, "textNodeName")
            
         end
       indexid4656856 += 1
            end
      assertEqualsAutoCase("element", "childNames", expected, actual)
        
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/hc_nodereplacechildnewchildexists"
  end
end

