
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     The "getAttributeNode(name)" method retrieves an
#    attribute node by name.
#    
#    Retrieve the attribute "domestic" from the last child
#    of the first employee.  Since the method returns an
#    Attr object, the "name" can be examined to ensure the
#    proper attribute was retrieved.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-217A91B8]
##
DOMTestCase('elementgetattributenode') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staff", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_elementgetattributenode
    doc = nil
    elementList = nil
    testEmployee = nil
    domesticAttr = nil
    name = nil
    doc = load_document("staff", true)
      elementList = doc.getElementsByTagName("address")
      testEmployee = elementList.item(0)
      domesticAttr = testEmployee.getAttributeNode("domestic")
      name = domesticAttr.nodeName()
      assert_equal("domestic", name, "elementGetAttributeNodeAssert")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/elementgetattributenode"
  end
end

