
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001-2004 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     Retrieve the second acronym element and invoke
#     the cloneNode method.   The
#     duplicate node returned by the method should copy the
#     attributes associated with this node.
# @author Curt Arnold
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-84CF096]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=236]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=184]
##
DOMTestCase('hc_nodecloneattributescopied') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "hc_staff", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_hc_nodecloneattributescopied
    doc = nil
    elementList = nil
    addressNode = nil
    clonedNode = nil
    attributes = nil
    attributeNode = nil
    attributeName = nil
    result = []
      
    htmlExpected = []
      htmlExpected << "class"
      htmlExpected << "title"
      
    expected = []
      expected << "class"
      expected << "title"
      expected << "dir"
      
    doc = load_document("hc_staff", true)
      elementList = doc.getElementsByTagName("acronym")
      addressNode = elementList.item(1)
      clonedNode = addressNode.cloneNode(false)
      attributes = clonedNode.attributes()
      indexid3941859 = 0
    while (indexid3941859 < attributes.length)
      attributeNode = attributes.item(indexid3941859)
    attributeName = attributeNode.nodeName()
      result << attributeName
      indexid3941859 += 1
            end
      
      if (("text/html" == getContentType()))
        assertEqualsIgnoreCase("nodeNames_html", htmlExpected, result)

          else
            assert_equal(expected, result, "nodeNames")
            
         end
       
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/hc_nodecloneattributescopied"
  end
end

