
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001-2004 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require 'dom_test_case'

###
# Collect the element names from Node.childNodes and check against expectations.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1451460987]
##
DOMTestCase('nodechildnodes') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staff", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_nodechildnodes
    doc = nil
    elementList = nil
    employeeNode = nil
    childNodes = nil
    childNode = nil
    childType = nil
    childName = nil
    elementNames = []
      
    expectedElementNames = []
      expectedElementNames << "employeeId"
      expectedElementNames << "name"
      expectedElementNames << "position"
      expectedElementNames << "salary"
      expectedElementNames << "gender"
      expectedElementNames << "address"
      
    doc = load_document("staff", false)
      elementList = doc.getElementsByTagName("employee")
      employeeNode = elementList.item(1)
      childNodes = employeeNode.childNodes()
      indexid5389346 = 0
    while (indexid5389346 < childNodes.length)
      childNode = childNodes.item(indexid5389346)
    childType = childNode.nodeType()
      
      if (equals(1, childType))
        childName = childNode.nodeName()
      elementNames << childName
      
         end
       indexid5389346 += 1
            end
      assert_equal(expectedElementNames, elementNames, "elementNames")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/nodechildnodes"
  end
end

