
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001-2003 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     The "setAttributeNode(newAttr)" method adds a new 
#    attribute to the Element.  
#    
#    Retrieve first address element and add
#    a new attribute node to it by invoking its         
#    "setAttributeNode(newAttr)" method.  This test makes use
#    of the "createAttribute(name)" method from the Document
#    interface.
# @author Curt Arnold
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-887236154]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=243]
##
DOMTestCase('hc_elementcreatenewattribute') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "hc_staff", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_hc_elementcreatenewattribute
    doc = nil
    elementList = nil
    testAddress = nil
    newAttribute = nil
    oldAttr = nil
    districtAttr = nil
    attrVal = nil
    doc = load_document("hc_staff", true)
      elementList = doc.getElementsByTagName("acronym")
      testAddress = elementList.item(0)
      newAttribute = doc.createAttribute("lang")
      oldAttr = testAddress.setAttributeNode(newAttribute)
      assert_nil(oldAttr, "old_attr_doesnt_exist")
      districtAttr = testAddress.getAttributeNode("lang")
      assert_not_nil(districtAttr, "new_district_accessible")
      attrVal = testAddress.getAttribute("lang")
      assert_equal("", attrVal, "attr_value")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/hc_elementcreatenewattribute"
  end
end

