
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require 'dom_test_case'

###
#     The NodeList returned by the "getChildNodes()" method
#     is live.   Changes on the node's children are immediately
#     reflected on the nodes returned in the NodeList.
#     
#     Create a NodeList of the children of the second employee
#     and then add a newly created element that was created
#     by the "createElement()" method(Document Interface) to
#     the second employee by using the "appendChild()" method.
#     The length of the NodeList should reflect this new
#     addition to the child list.   It should return the value 14.
# @author Curt Arnold
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1451460987]
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-184E7107]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=246]
# see[http://www.w3.org/Bugs/Public/show_bug.cgi?id=247]
##
DOMTestCase('hc_nodechildnodesappendchild') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "hc_staff", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_hc_nodechildnodesappendchild
    doc = nil
    elementList = nil
    employeeNode = nil
    childList = nil
    createdNode = nil
    childNode = nil
    childName = nil
    childType = nil
    textNode = nil
    actual = []
      
    expected = []
      expected << "em"
      expected << "strong"
      expected << "code"
      expected << "sup"
      expected << "var"
      expected << "acronym"
      expected << "br"
      
    doc = load_document("hc_staff", true)
      elementList = doc.getElementsByTagName("p")
      employeeNode = elementList.item(1)
      childList = employeeNode.childNodes()
      createdNode = doc.createElement("br")
      employeeNode = employeeNode.appendChild(createdNode)
      indexid3925309 = 0
    while (indexid3925309 < childList.length)
      childNode = childList.item(indexid3925309)
    childName = childNode.nodeName()
      childType = childNode.nodeType()
      
      if (equals(1, childType))
        actual << childName
      
          else
            assert_equal(3, childType, "textNodeType")
            
         end
       indexid3925309 += 1
            end
      assertEqualsAutoCase("element", "childElements", expected, actual)
        
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/hc_nodechildnodesappendchild"
  end
end

