
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin

Copyright (c) 2001-2004 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

=end
#

require 'dom_test_case'

###
#     Retrieve the textual data from the last child of the 
#     second employee.   That node is composed of two   
#     EntityReference nodes and two Text nodes.   After
#     the content node is parsed, the "address" Element
#     should contain four children with each one of the
#     EntityReferences containing one child.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1451460987]
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-11C98490]
# see[http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-745549614]
##
DOMTestCase('textparseintolistofelements') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staff", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_textparseintolistofelements
    doc = nil
    elementList = nil
    addressNode = nil
    childList = nil
    child = nil
    length = nil
    value = nil
    grandChild = nil
    result = []
      
    expectedNormal = []
      expectedNormal << "1900 Dallas Road"
      expectedNormal << " Dallas, "
      expectedNormal << "Texas"
      expectedNormal << "\n 98554"
      
    expectedExpanded = []
      expectedExpanded << "1900 Dallas Road Dallas, Texas\n 98554"
      
    doc = load_document("staff", false)
      elementList = doc.getElementsByTagName("address")
      addressNode = elementList.item(1)
      childList = addressNode.childNodes()
      length = childList.length()
      indexid6982212 = 0
    while (indexid6982212 < childList.length)
      child = childList.item(indexid6982212)
    value = child.nodeValue()
      
      if ((value == nil))
        grandChild = child.firstChild()
      assert_not_nil(grandChild, "grandChildNotNull")
      value = grandChild.nodeValue()
      result << value
      
          else
            result << value
      
         end
       indexid6982212 += 1
            end
      
      if (equals(4, length))
        assert_equal(expectedNormal, result, "assertEqNormal")
            
          else
            assert_equal(expectedExpanded, result, "assertEqCoalescing")
            
         end
       
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/textparseintolistofelements"
  end
end

