
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#  The method hasAttributes returns whether this node (if it is an element) has any attributes.
#  Create a new Document, Element and Attr node.  Add the Attr to the Element and append the 
#  Element to the Document.  Retreive the newly created element node from the document and check
#  if it has attributes using hasAttributes.
# @author IBM
# @author Neil Delima
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#ID-NodeHasAttrs]
##
DOMTestCase('nodehasattributes04') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
=begin
      org.w3c.domts.DocumentBuilderSetting[] settings = 
          new org.w3c.domts.DocumentBuilderSetting[] {
org.w3c.domts.DocumentBuilderSetting.namespaceAware
        };
        DOMTestDocumentBuilderFactory testFactory = factory.newInstance(settings)
        setFactory(testFactory)
=end

    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staffNS", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_nodehasattributes04
    doc = nil
    newDoc = nil
    docType = nil;

    domImpl = nil
    element = nil
    elementTest = nil
    elementDoc = nil
    attribute = nil
    setNode = nil
    appendedChild = nil
    elementList = nil
    hasAttributes = nil
    doc = load_document("staffNS", false)
      domImpl = doc.getImplementation()
      
      
      attribute = newDoc.createAttribute("attr")
      setNode = element.setAttributeNode(attribute)
      elementDoc = newDoc.documentElement()
      appendedChild = elementDoc.appendChild(element)
      
      elementTest = elementList.item(0)
      
      assertTrue("nodehasattributes04", hasAttributes)
      
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/nodehasattributes04"
  end
end

