
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     The "getOwnerElement()" will return the Element node this attribute
#   is attached to or null if this attribute is not in use.  
#   Get the "domestic" attribute from the first "address" node.
#   Apply the "getOwnerElement()" method to get the Element associated 
#   with the attribute.  The value returned should be "address".
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#ID-F68D095]
##
DOMTestCase('ownerElement01') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staff", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_ownerElement01
    doc = nil
    addressList = nil
    testNode = nil
    attributes = nil
    domesticAttr = nil
    elementNode = nil
    name = nil
    doc = load_document("staff", false)
      addressList = doc.getElementsByTagName("address")
      testNode = addressList.item(0)
      attributes = testNode.attributes()
      domesticAttr = attributes.getNamedItem("domestic")
      
      name = elementNode.nodeName()
      assert_equal("address", name, "throw_Equals")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/ownerElement01"
  end
end

