
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#  The method createElementNS creates an element of the given valid qualifiedName and NamespaceURI. 
#  
#  Invoke the createElementNS method on this Document object with a valid namespaceURI
#  and qualifiedName.  Check if a valid Element object is returned with the same node attributes.
# @author IBM
# @author Neil Delima
# see[http://www.w3.org/TR/DOM-Level-2-Core/core]
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#ID-DocCrElNS]
##
DOMTestCase('documentcreateelementNS01') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staffNS", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_documentcreateelementNS01
    doc = nil
    element = nil
    namespaceURI = "http://www.w3.org/DOM/Test/level2";
    qualifiedName = "XML:XML";
    nodeName = nil
    nsURI = nil
    localName = nil
    prefix = nil
    tagName = nil
    doc = load_document("staffNS", false)
      
      nodeName = element.nodeName()
      
      
      
      tagName = element.tagName()
      assert_equal("XML:XML", nodeName, "documentcreateelementNS01_nodeName")
            assert_equal("http://www.w3.org/DOM/Test/level2", nsURI, "documentcreateelementNS01_namespaceURI")
            assert_equal("XML", localName, "documentcreateelementNS01_localName")
            assert_equal("XML", prefix, "documentcreateelementNS01_prefix")
            assert_equal("XML:XML", tagName, "documentcreateelementNS01_tagName")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/documentcreateelementNS01"
  end
end

