
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     The "getNamedItemNS(namespaceURI,localName)" method for a 
#    NamedNodeMap should return null
#    if parameters do not identify any node in this map.
#    
#    Retrieve a list of elements with tag name "address".
#    Access the second element from the list and get its attributes.
#    Try to retrieve an attribute node with local name "domest"
#    and namespace uri "http://www.usa.com" with
#    method getNamedItemNS(namespaceURI,localName).
#    This should return null because "domest" does not match any local names in this map.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#ID-getNamedItemNS]
##
DOMTestCase('getNamedItemNS02') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staffNS", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_getNamedItemNS02
    namespaceURI = "http://www.usa.com";
    localName = "domest";
    doc = nil
    elementList = nil
    testEmployee = nil
    attributes = nil
    newAttr = nil
    doc = load_document("staffNS", false)
      elementList = doc.getElementsByTagName("address")
      testEmployee = elementList.item(1)
      attributes = testEmployee.attributes()
      
      assert_nil(newAttr, "throw_Null")
      
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/getNamedItemNS02"
  end
end

