
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     The "removeNamedItemNS(namespaceURI,localName)" method for a 
#    NamedNodeMap should raise NOT_FOUND_ERR DOMException if
#    there is no node with the specified namespaceURI and localName in this map.
#    
#    Retrieve a list of elements with tag name "address".
#    Access the second element from the list and get its attributes.
#    Try to remove an attribute node with local name "domest"
#    and namespace uri "http://www.usa.com" with 
#    method removeNamedItemNS(namespaceURI,localName).
#    This should raise NOT_FOUND_ERR DOMException.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#xpointer(id('ID-258A00AF')/constant[@name='NOT_FOUND_ERR'])]
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#ID-removeNamedItemNS]
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#xpointer(id('ID-removeNamedItemNS')/raises/exception[@name='DOMException']/descr/p[substring-before(.,':')='NOT_FOUND_ERR'])]
##
DOMTestCase('removeNamedItemNS02') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staffNS", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_removeNamedItemNS02
    namespaceURI = "http://www.usa.com";
    localName = "domest";
    doc = nil
    elementList = nil
    testAddress = nil
    attributes = nil
    removedNode = nil
    doc = load_document("staffNS", true)
      elementList = doc.getElementsByTagName("address")
      testAddress = elementList.item(1)
      attributes = testAddress.attributes()
      
    begin
      success = false;
      begin
        
      rescue Nokogiri::XML::DOMException => ex
        success = (ex.code == Nokogiri::XML::DOMException::NOT_FOUND_ERR)
      end 
      assert(success, "throw_NOT_FOUND_ERR")
    end

  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/removeNamedItemNS02"
  end
end

