
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium,

(Massachusetts Institute of Technology, Institut National de

Recherche en Informatique et en Automatique, Keio University). All

Rights Reserved. This program is distributed under the W3C's Software

Intellectual Property License. This program is distributed in the

hope that it will be useful, but WITHOUT ANY WARRANTY; without even

the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR

PURPOSE.

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#
###
 # 
##
