
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     The "setNamedItemNS(arg)" method for a 
#    NamedNodeMap should add a node using its namespaceURI and localName given that
#    there is no existing node with the same namespaceURI and localName in the map.
#    
#    Create an attr node with namespaceURI "http://www.nist.gov",qualifiedName
#    "prefix:newAttr" and value "newValue".
#    Invoke method setNamedItemNS(arg) on the map of the first "address"
#    element where arg is identified by the namespaceURI and qualifiedName
#    from above.  Method should return the newly added attr node.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#ID-F68D080]
##
DOMTestCase('setNamedItemNS03') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staffNS", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_setNamedItemNS03
    namespaceURI = "http://www.nist.gov";
    qualifiedName = "prefix:newAttr";
    doc = nil
    arg = nil
    elementList = nil
    testAddress = nil
    attributes = nil
    retnode = nil
    value = nil
    setNode = nil
    doc = load_document("staffNS", true)
      
      arg.nodeValue = "newValue"
      elementList = doc.getElementsByTagName("address")
      testAddress = elementList.item(0)
      attributes = testAddress.attributes()
      
      
      value = retnode.nodeValue()
      assert_equal("newValue", value, "throw_Equals")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/setNamedItemNS03"
  end
end

