
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     The "getElementsByTagNameNS(namespaceURI,localName)" method returns a NodeList
#    of all descendant Elements with a given local name and namespace URI in the
#    order in which they are encountered in a preorder traversal of this Element tree.
#    
#    Create a NodeList of all the descendant elements
#    using the special value "*" as the namespaceURI and "address" as the 
#    localName.
#    The method should return a NodeList of Elements that have
#    "address" as the local name.  
#    This test is derived from getElementsByTagNameNS04
# @author Curt Arnold
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#ID-1938918D]
##
DOMTestCase('getElementsByTagNameNS11') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
=begin
      org.w3c.domts.DocumentBuilderSetting[] settings = 
          new org.w3c.domts.DocumentBuilderSetting[] {
org.w3c.domts.DocumentBuilderSetting.namespaceAware
        };
        DOMTestDocumentBuilderFactory testFactory = factory.newInstance(settings)
        setFactory(testFactory)
=end

    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staffNS", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_getElementsByTagNameNS11
    doc = nil
    docElem = nil
    elementList = nil
    child = nil
    childName = nil
    result = []
      
    expectedResult = []
      expectedResult << "address"
      expectedResult << "address"
      expectedResult << "address"
      expectedResult << "emp:address"
      expectedResult << "address"
      
    doc = load_document("staffNS", false)
      docElem = doc.documentElement()
      
      indexid2317466 = 0
    while (indexid2317466 < elementList.length)
      child = elementList.item(indexid2317466)
    childName = child.nodeName()
      result << childName
      indexid2317466 += 1
            end
      assert_equal(expectedResult, result, "nodeNames")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/getElementsByTagNameNS11"
  end
end

