
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001-2004 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#  The importNode method imports a node from another document to this document. 
#  The returned node has no parent; (parentNode is null). The source node is not 
#  altered or removed from the original document but a new copy of the source node
#  is created.
#  
#  Using the method importNode with deep=true/false, import a entity nodes ent2 and ent6
#  from this document to a new document object.  Verify if the nodes have been 
#  imported correctly by checking the nodeNames of the imported nodes and public and system ids.
# @author IBM
# @author Neil Delima
# see[http://www.w3.org/TR/DOM-Level-2-Core/core]
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#Core-Document-importNode]
##
DOMTestCase('documentimportnode19') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
=begin
      org.w3c.domts.DocumentBuilderSetting[] settings = 
          new org.w3c.domts.DocumentBuilderSetting[] {
org.w3c.domts.DocumentBuilderSetting.namespaceAware
        };
        DOMTestDocumentBuilderFactory testFactory = factory.newInstance(settings)
        setFactory(testFactory)
=end

    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staffNS", true)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_documentimportnode19
    doc = nil
    docTypeNull = nil;

    docImp = nil
    domImpl = nil
    docType = nil
    nodeMap = nil
    entity2 = nil
    entity6 = nil
    entityImp2 = nil
    entityImp6 = nil
    nodeName = nil
    systemId = nil
    notationName = nil
    nodeNameImp = nil
    systemIdImp = nil
    notationNameImp = nil
    doc = load_document("staffNS", true)
      domImpl = doc.getImplementation()
      docType = doc.doctype()
      
      nodeMap = docType.entities()
      assert_not_nil(nodeMap, "entitiesNotNull")
      entity2 = nodeMap.getNamedItem("ent2")
      entity6 = nodeMap.getNamedItem("ent6")
      
      
      nodeName = entity2.nodeName()
      nodeNameImp = entityImp2.nodeName()
      assert_equal(nodeName, nodeNameImp, "documentimportnode19_Ent2NodeName")
            nodeName = entity6.nodeName()
      nodeNameImp = entityImp6.nodeName()
      assert_equal(nodeName, nodeNameImp, "documentimportnode19_Ent6NodeName")
            systemId = entity2.systemId()
      systemIdImp = entityImp2.systemId()
      assert_equal(systemId, systemIdImp, "documentimportnode19_Ent2SystemId")
            systemId = entity6.systemId()
      systemIdImp = entityImp6.systemId()
      assert_equal(systemId, systemIdImp, "documentimportnode19_Ent6SystemId")
            notationName = entity2.notationName()
      notationNameImp = entityImp2.notationName()
      assert_equal(notationName, notationNameImp, "documentimportnode19_Ent2NotationName")
            notationName = entity6.notationName()
      notationNameImp = entityImp6.notationName()
      assert_equal(notationName, notationNameImp, "documentimportnode19_Ent6NotationName")
            
  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/documentimportnode19"
  end
end

