
###
# This Ruby source file was generated by test-to-ruby.xsl
# and is a derived work from the source document.
# The source document contained the following notice:
=begin


Copyright (c) 2001-2004 World Wide Web Consortium, 
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University).  All 
Rights Reserved.  This program is distributed under the W3C's Software
Intellectual Property License.  This program is distributed in the 
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
PURPOSE.  

See W3C License http://www.w3.org/Consortium/Legal/ for more details.


=end
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '..', 'helper'))

###
#     The "hasAttributeNS()" method for an Element should 
#    return false if the element does not have an attribute with the given local name 
#    and/or namespace URI specified on this element or does not have a default value.
#    Retrieve the first "emp:address" element.
#    The boolean value returned by the "hasAttributeNS()" should be false 
#    since the attribute does not have a default value.
# @author NIST
# @author Mary Brady
# see[http://www.w3.org/TR/DOM-Level-2-Core/core#ID-ElHasAttrNS]
##
DOMTestCase('hasAttributeNS03') do

  ###
  # Constructor.
  # @param factory document factory, may not be null
  # @throws org.w3c.domts.DOMTestIncompatibleException Thrown if test is not compatible with parser configuration
  ##
  def setup
    ##
    ##   check if loaded documents are supported for content type
    ##
    contentType = getContentType()
    preload(contentType, "staffNS", false)
  end

  ###
  # Runs the test case.
  # @throws Throwable Any uncaught exception causes test to fail
  #
  def test_hasAttributeNS03
    localName = "blank";
    namespaceURI = "http://www.nist.gov";
    doc = nil
    elementList = nil
    testNode = nil
    state = nil
    doc = load_document("staffNS", false)
      elementList = doc.getElementsByTagName("emp:address")
      testNode = elementList.item(0)
      assert_not_nil(testNode, "empAddrNotNull")
      
      assertFalse("throw_False", state)

  end

  ###
  # Gets URI that identifies the test.
  # @return uri identifier of test
  #
  def targetURI
    "http://www.w3.org/2001/DOM-Test-Suite/tests/Level-1/hasAttributeNS03"
  end
end

