require 'nokogiri/dom/element'
require 'nokogiri/dom/node'
require 'nokogiri/dom/document'
require 'nokogiri/dom/node_set'
require 'nokogiri/dom/text'
require 'nokogiri/dom/named_node_map'
require 'nokogiri/dom/notation'
require 'nokogiri/dom/character_data'
